import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import clsx from 'clsx'

import { DraftModeScript } from '@makeswift/runtime/next/server'

import '@/lib/makeswift/components'
import { MakeswiftProvider } from '@/lib/makeswift/provider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const playwriteHrLijeva = localFont({ 
  src: '../fonts/Playwrite_HR_Lijeva/PlaywriteHRLijeva-VariableFont_wght.ttf',
  variable: '--font-playwrite-hr-lijeva',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <DraftModeScript />
      </head>
      <body className={clsx(playwriteHrLijeva.className, inter.className)}>
        <MakeswiftProvider>{children}</MakeswiftProvider>
      </body>
    </html>
  )
}
